DjangoLab/iswork/core/urls.py
from django.contrib import admin
from django.urls import path
from core import views

urlpatterns = [
    path('', views.HomeListView.as_view(), name='home'),
    path('detail/<int:pk>', views.HomeDetailView.as_view(), name='detail_page'),
    path('edit-page', views.ArticleCreateView.as_view(), name='edit_page'),
    path('update-page/<int:pk>', views.ArticleUpdateView.as_view(), name='update_page'),
    path('delete-page/<int:pk>', views.delete_page, name='delete_page'),
    path('login', views.MyprojectLoginView.as_view(), name='login_page'),
    path('register', views.RegisterUserView.as_view(), name='register_page'),
    path('logout/', views.MyProjectLogout.as_view(), name='logout'),
    path('like/<int:pk>/', views.LikeView.as_view(), name='like_article'),
]

DjangoLab/iswork/iswork/urls.py
from django.contrib import admin
from django.urls import path, include

# маршруты, которые связывают URL-адреса с конкретными функциями или классами.
urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
]

DjangoLab/iswork/core/models.py
from django.db import models
from django.contrib.auth.models import User

# определения моделей данных проекта. Модели представляют собой структуру данных, которые будут храниться в базе данных.

class Advantage(models.Model):
    author = models.ForeignKey(User, on_delete = models.CASCADE, verbose_name='Владелец статьи', blank = True, null = True )
    create_date = models.DateTimeField(auto_now=True)
    name = models.CharField(max_length=200, verbose_name='Название')
    text = models.TextField(verbose_name='Текст')
    
    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name='Достижение'
        verbose_name_plural='Статьи'

class Comments(models.Model):
    article = models.ForeignKey(Advantage, on_delete = models.CASCADE, verbose_name='Достижение', blank = True, null = True,related_name='comments_articles' )
    author = models.ForeignKey(User, on_delete = models.CASCADE, verbose_name='Автор комментария', blank = True, null = True )
    create_date = models.DateTimeField(auto_now=True)
    text = models.TextField(verbose_name='Текст комментария')
    status = models.BooleanField(verbose_name='Видимость статьи', default=False)

class Like(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Пользователь')
    article = models.ForeignKey(Advantage, on_delete=models.CASCADE, verbose_name='Статья')

    class Meta:
        unique_together = ('user', 'article')  # Один пользователь может лайкнуть статью только один раз

    def __str__(self):
        return f"{self.user.username} likes {self.article.name}"

DjangoLab/iswork/core/forms.py
from django import forms
from django.forms import Textarea
from .models import Advantage, Comments
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User

class AdvantageForm(forms.ModelForm):
    class Meta:
        model = Advantage
        fields = ('name','text')
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'

class AuthUserForm(AuthenticationForm, forms.ModelForm):
    class Meta:
        model = User
        fields = ('username','password')
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'

class RegisterUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username','password')
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'
    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user
    
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comments
        fields = ('text',)
    def __init__(self,*args,**kwargs):
        super().__init__(*args,**kwargs)
        for field in self.fields:
            self.fields[field].widget.attrs['class'] = 'form-control'
        self.fields['text'].widget = Textarea(attrs={'rows':5})

DjangoLab/iswork/core/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.views.generic import ListView, DetailView,CreateView, UpdateView,DeleteView
from django.views.generic.edit import FormMixin
from .models import Advantage, Like
from .forms import AdvantageForm, AuthUserForm, RegisterUserForm, CommentForm
from django.urls import reverse, reverse_lazy
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect

# файл содержит функции, которые обрабатывают HTTP-запросы и возвращают HTTP-ответы.
# Функции в этом файле часто взаимодействуют с моделями данных.
class CustomSuccessMessageMixin:
    @property
    def success_msg(self):
        return False
        
    def form_valid(self,form):
        messages.success(self.request, self.success_msg)
        return super().form_valid(form)
    def get_success_url(self):
        return '%s?id=%s' % (self.success_url, self.object.id)

class HomeListView(ListView):
    model = Advantage
    template_name = 'index.html'
    context_object_name = 'list_articles'

    def get_queryset(self):
        queryset = super().get_queryset()
        filter_type = self.request.GET.get('filter')

        if filter_type == 'date':
            queryset = queryset.order_by('-create_date')  # Сортировка по дате создания
        elif filter_type == 'title':
            queryset = queryset.order_by('name')  # Сортировка по заголовку
        else:
            queryset = queryset.order_by('-create_date')  # По умолчанию сортировка по дате создания

        return queryset
    


class LikeView(View):
    def post(self, request, pk):
        article = Advantage.objects.get(pk=pk)
        like, created = Like.objects.get_or_create(user=request.user, article=article)
        if created:
            messages.success(request, 'Вы понравились статью!')
        else:
            messages.info(request, 'Вы уже понравились этой статье.')
        return redirect('detail_page', pk=article.pk)


class HomeDetailView(CustomSuccessMessageMixin, FormMixin, DetailView):
    model = Advantage
    template_name = 'detail.html'
    context_object_name = 'get_article'
    form_class = CommentForm
    success_msg = 'Комментарий создан!'

    def get_success_url(self, **kwargs):
        return reverse_lazy('detail_page', kwargs={'pk':self.get_object().id})

    def post(self,request, *args, **kwargs):
        form = self.get_form()
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)
        
    def form_valid(self,form):
        self.object = form.save(commit=False)
        self.object.article = self.get_object()
        self.object.author = self.request.user
        self.object.save()
        return super().form_valid(form)

class ArticleCreateView(LoginRequiredMixin, CustomSuccessMessageMixin, CreateView):
    login_url = reverse_lazy('login_page')
    model = Advantage
    template_name = 'edit_page.html'
    form_class = AdvantageForm
    success_url = reverse_lazy('edit_page')
    success_msg = 'Запись создана'
    def get_context_data(self,**kwargs):
        kwargs['list_articles'] = Advantage.objects.all().order_by('-id')
        return super().get_context_data(**kwargs)
    def form_valid(self,form):
        self.object = form.save(commit=False)
        self.object.author = self.request.user
        self.object.save()
        return super().form_valid(form)

class ArticleUpdateView(LoginRequiredMixin, CustomSuccessMessageMixin,UpdateView):
    model = Advantage
    template_name = 'edit_page.html'
    form_class = AdvantageForm
    success_url = reverse_lazy('edit_page')
    success_msg = 'Запись успешно обновлена'
    def get_context_data(self,**kwargs):
        kwargs['update'] = True
        return super().get_context_data(**kwargs)
    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        if self.request.user != kwargs['instance'].author:
            return self.handle_no_permission()
        return kwargs

def delete_page(request, pk):
     get_article = Advantage.objects.get(pk=pk)
     get_article.delete()
     return redirect(reverse('edit_page'))

class MyprojectLoginView(LoginView):
    template_name = 'login.html'
    form_class = AuthUserForm
    success_url = reverse_lazy('edit_page')
    def get_success_url(self):
        return self.success_url

class RegisterUserView(CreateView):
    model = User
    template_name = 'register_page.html'
    form_class = RegisterUserForm
    success_url = reverse_lazy('edit_page')
    success_msg = 'Пользователь успешно создан'
    def form_valid(self,form):
        form_valid = super().form_valid(form)
        username = form.cleaned_data["username"]
        password = form.cleaned_data["password"]
        aut_user = authenticate(username=username,password=password)
        login(self.request, aut_user)
        return form_valid
    

class MyProjectLogout(LogoutView):
    next_page = reverse_lazy('edit_page')

DjangoLab/iswork/core/templates/detail.html
{% extends 'index.html' %}
{% block title %}Детали достижения{% endblock %}

{% block content %}
<p><a href='/'>Вернуться назад</a></p>
<p>Дата создания: {{ get_article.create_date }}</p>
<p>Название: {{ get_article.name }}</p>
<p>Текст: {{ get_article.text }}</p>

<!-- Отображение количества лайков -->
<p>Лайки: {{ get_article.like_set.count }}</p>

<!-- Форма для лайка -->
{% if request.user.is_authenticated %}
<form method="post" action="{% url 'like_article' get_article.id %}">
    {% csrf_token %}
    <button type="submit" class="btn btn-primary">Понравилось</button>
</form>
{% else %}
<p>Чтобы поставить лайк, <a href="{% url 'login_page' %}">войдите в систему</a>.</p>
{% endif %}

<hr>
<p>Комментарии ({{ get_article.comments_articles.count }})</p>
<ul>
    {% for item in get_article.comments_articles.all %}
    <li>
        Дата написания: {{ item.create_date }}<br>
        Автор: {{ item.author }}<br>
        {{ item.text }}
    </li>
    {% endfor %}
</ul>

<div class="col-4">
    <h3>Добавить комментарий</h3>
    <form id='add_form' method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Добавить</button>
    </form>
</div>
{% endblock %}


DjangoLab/iswork/core/templates/edit_page.html
{% extends 'index.html' %}
{% block content %}
<h1 class="mt-4">Админ панель</h1>

<!-- Кнопка-триггер модального окна для добавления нового достижения -->
<button type="button" class="btn btn-primary" id="openModalBtn">
    Добавить новое достижение
</button>

{% if success %}
<p style="color:red">Запись добавлена</p>
{% endif %}

{% if update %}
    {% if success_update %}
    <p style="color:red">Данные обновлены</p>
    {% endif %}
    <p>Страница редактирования</p>
    <p><a href="{% url 'edit_page' %}">Вернуться назад</a></p>
{% endif %}

<!-- Таблица достижений -->
<table class="table">
    <thead>
        <tr>
            <th scope="col">id</th>
            <th scope="col">Дата создания</th>
            <th scope="col">Название</th>
            <th scope="col">Редактирование</th>
            <th scope="col">Удаление</th>
        </tr>
    </thead>
    <tbody>
        {% for i in list_articles %}
        <tr>
            <th>{{ i.id }}</th>
            <td>{{ i.create_date|date:'d.m.Y' }} - {{ i.author }}</td>
            <td>{{ i.name }}</td>
            <td><a href="{% url 'update_page' i.id %}">Редактировать</a></td>
            <td><a href="{% url 'delete_page' i.id %}">Удалить</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>

<!-- Модальное окно для добавления нового достижения -->
<div id="addAchievementModal" class="modal" style="display: none;">
    <div class="modal-content">
        <span class="close">&times;</span>
        <h1>Добавить новое достижение</h1>
        <form id='add_form' method="post">
            {% csrf_token %}
            {{ form.as_p }}  <!-- Используем as_p для лучшего отображения формы -->
            <button type="submit" class="btn btn-primary">Сохранить</button>
        </form>
    </div>
</div>

<script>
    document.addEventListener('DOMContentLoaded', function() {
        // Получаем модальное окно
        var modal = document.getElementById("addAchievementModal");

        // Получаем кнопку, которая открывает модальное окно
        var btn = document.getElementById("openModalBtn");

        // Получаем элемент <span>, который закрывает модальное окно
        var span = document.getElementsByClassName("close")[0];

        // Когда пользователь нажимает на кнопку, открываем модальное окно
        btn.onclick = function() {
            modal.style.display = "block";
        }

        // Когда пользователь нажимает на <span> (x), закрываем модальное окно
        span.onclick = function() {
            modal.style.display = "none";
        }

        // Когда пользователь нажимает в любом месте вне модального окна, закрываем его
        window.onclick = function(event) {
            if (event.target == modal) {
                modal.style.display = "none";
            }
        }
    });
</script>
{% endblock %}

DjangoLab/iswork/core/templates/index.html
<!doctype html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Мои достижения</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f0f0f0;
            margin: 0;
            padding: 20px;
        }

        .nav {
            background-color: #e0e0e0;
            padding: 10px;
            margin-bottom: 20px;
        }

        .nav-item {
            display: inline;
            margin-right: 15px;
        }

        .nav-link {
            text-decoration: none;
            color: #333;
            padding: 5px 10px;
        }

        .nav-link.active {
            font-weight: bold;
            text-decoration: underline;
        }

        h1 {
            margin-top: 20px;
            font-size: 24px;
        }

        .filter {
            margin: 20px 0;
            font-size: 14px;
        }

        .achievement {
            background-color: #ffffff;
            border: 1px solid #ccc;
            padding: 10px;
            margin-bottom: 10px;
            border-radius: 5px;
        }

        .achievement b {
            display: block;
            margin-bottom: 5px;
        }

        .sort {
            cursor: pointer;
            margin-left: 5px;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="nav">
            <ul>
                <li class="nav-item">
                    {% url 'home' as url_home %}
                    <a class="nav-link {% if url_home == request.path %} active {% endif %}" href="{{url_home}}">Главная</a>
                </li>
                <li class="nav-item">
                    {% url 'edit_page' as url_edit_page %}
                    <a class="nav-link {% if url_edit_page == request.path %} active {% endif %}" href="{{url_edit_page}}">Создание/ред/удал</a>
                </li>
                {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <form method="POST" action="{% url 'logout' %}" style="display:inline;">
                            {% csrf_token %}
                            <button class="nav-link" type="submit">Выход</button>
                        </form>
                    </li>
                {% else %}
                    <li class="nav-item">
                        {% url 'login_page' as url_login_page %}
                        <a class="nav-link {% if url_login_page == request.path %} active {% endif %}" href="{{url_login_page}}">Авторизация</a>
                    </li>
                    <li class="nav-item">
                        {% url 'register_page' as url_register_page %}
                        <a class="nav-link {% if url_register_page == request.path %} active {% endif %}" href="{{url_register_page}}">Регистрация</a>
                    </li>
                {% endif %}
            </ul>
        </div>

        {% block content %}
        <h1>Достижения</h1>

        {% if request.path == '/' %}
        <div class="filter">
            <span>Фильтрация: </span>
            <a href="?filter=date">По дате создания</a><span class="sort">&#8595;</span>
            <a href="?filter=title">По заголовку</a><span class="sort">&#8595;</span>
            <a href="{% url 'home' %}">Сбросить фильтры</a>
        </div>
        {% endif %}

        {% for i in list_articles %}
        <div class="achievement">
            <b>{{i.create_date}}</b>
            <span>{{i.name}}</span>
            <span>{{i.text}}</span>
            <span style="float:right;"><a href="/detail/{{i.id}}">перейти к статье</a></span>
        </div>
        {% endfor %}
        {% endblock %}
    </div>
</body>
</html>



DjangoLab/iswork/core/templates/login.html
{% extends 'index.html' %}
{% block title %}Авторизация{% endblock %}

{% block content %}
<h1 class="mt-4">Авторизация</h1>
<p><a href='/'>Вернуться назад</a></p>
<div class="col-4">
    <form id='add_form' method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary mt-4">Сохранить</button>
    </form>
</div>
{% endblock %}


DjangoLab/iswork/core/templates/register_page.html
{% extends 'index.html' %}
{% block title %}Регистрация{% endblock %}

{% block content %}
<h1 class="mt-4">Регистрация</h1>
<p><a href='/'>Вернуться назад</a></p>
<div class="col-4">
    <form id='add_form' method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary mt-4">Сохранить</button>
    </form>
</div>
{% endblock %}
